;		assembly program using interrupts to toggle led and port pins
PIN_TOGGLE EQU P1.2
LED	EQU P1.1
	ORG 0H
	LJMP MAIN
	ORG 0BH
ISR_T0:	CPL PIN_TOGGLE
	CJNE R1, #0, CONTINUE
	MOV R1,#15
	CPL LED
CONTINUE:	DEC R1
	MOV TL0,#0FDH
	MOV TH0,#87H
	CPL PIN_TOGGLE
	RETI
MAIN:MOV R1,#0
	MOV P1,R1
	MOV TMOD,#01H
	MOV TL0,#0FdH
	MOV TH0,#87H
	MOV IE,#82H
	SETB TR0
L1:	SJMP L1
	
